version: "3.8"

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}

  nodeapp:
    build: .
    image: tushar179/my-nodeapp
    ports:
    - 3000:3000
    environment:
    - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
    - MONGO_DB_PWD=${MONGO_DB_PWD}
    depends_on:
    - mongo

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_DB_USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_DB_PWD}
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PWD}
    - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PWD}@mongo:27017/